language: go

os:
  - linux
  - windows
  - osx

go:
  - 1.11.x
  - 1.12.x

matrix:
  allow_failures:
    - os: windows

before_install:
  - go get -t -v ./...

script:
  - go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
