language: go

os:
  - linux
  - windows
  - osx

go:
  - 1.11.x
  - 1.12.x

matrix:
  exclude:
    - os: windows
      go: 1.11.x

before_install:
  - go get -u golang.org/x/vgo

script:
  - vgo test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
